version: "3.8"
services:
  front:
    build: ./
    container_name: node
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
    ports:
      - 3000:3000
    tty: true
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
